feature:
  - '\[FEAT\]'
  - '[Ff]eature'
  - '기능'

bug:
  - '\[FIX\]'
  - '[Bb]ug'
  - '버그'
  - '오류'

refactor:
  - '\[REFACTOR\]'
  - '[Rr]efactor'
  - '리팩토'

docs:
  - '\[DOCS\]'
  - '[Dd]ocs'
  - '문서'

design:
  - '\[DESIGN\]'
  - '[Dd]esign'
  - '디자인'
  - 'UI'
  - 'UX'
