version: "3.8"

services:
  # 1. 스프링 부트
  spring-app:
    image: festival-api:1.0
    container_name: spring-app
    ports:
      - "8080:8080"
    # [.env 파일 읽기] 로컬 설정값들이 들어옵니다.
    env_file:
      - .env
    # .env에 뭐라고 적혀있든, 여기 설정이 이깁니다.
    environment:
      - SPRING_PROFILES_ACTIVE=prod            # 프로필 강제 적용
      - PROD_DB_HOST=postgres-container        # localhost -> 컨테이너 이름
      - PROD_REDIS_HOST=redis-container        # localhost -> 컨테이너 이름
      - LOGGING_FILE_NAME=/var/log/festival/application.log
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/var/log/festival
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    ports:
      - "${PROD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - "${PROD_REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis/data:/data
    command: >
      redis-server
      --requirepass ${PROD_REDIS_PASSWORD}
      --maxmemory 200mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec