spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본 실행환경 : local

  application:
    name: LocalFestival

  config:
    import: optional:file:.env[.properties]

  mvc:
    servlet:
      path: /api

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    encoding: UTF-8

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.jdbc.core: DEBUG
    com.localfestival: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 외부 API
external:
  api:
    festival:
      url: http://api.data.go.kr/openapi/tn_pubr_public_cltur_fstvl_api
      key: ${FESTIVAL_API_KEY}			
    tour:
      url: http://apis.data.go.kr/B551011/KorService2
      key: ${TOUR_API_KEY}

springdoc:
  # Swagger UI 설정
  swagger-ui:
    path: /swagger-ui.html              # Swagger UI 접근 경로
    tags-sorter: alpha                  # 태그 알파벳 순 정렬
    operations-sorter: alpha            # API 알파벳 순 정렬
    display-request-duration: true      # 요청 소요시간 표시
    groups-order: DESC                  # 그룹 정렬 순서
    disable-swagger-default-url: true   # swagger-ui default url 비활성화

  # API 문서 설정
  api-docs:
    path: /local-festival                     # API 문서 JSON 경로
    enabled: true                       # API 문서 활성화

  # 공통 설정
  default-consumes-media-type: application/json
  default-produces-media-type: application/json