spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}
      password: ${LOCAL_REDIS_PASSWORD}
      timeout: 3000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy}
      secret-key: ${AWS_SECRET_KEY:dummy}
    s3:
      bucket: ${AWS_S3_BUCKET:dummy-bucket}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false