spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # 기본 실행환경 : local

  application:
    name: LocalFestival

  config:
    import: optional:file:.env[.properties]

  mvc:
    servlet:
      path: /api

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    encoding: UTF-8

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.jdbc.core: DEBUG
    com.localfestival: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 외부 API
external:
  api:
    festival:
      url: https://api.data.go.kr/openapi/tn_pubr_public_cltur_fstvl_api
      key: ${FESTIVAL_API_KEY}			
    tour:
      url: https://apis.data.go.kr/B551011/KorService2
      key: ${TOUR_API_KEY}

