spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}
      password: ${LOCAL_REDIS_PASSWORD}
      timeout: 3000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
