global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    environment: "production"
    region: "ap-northeast-2"


scrape_configs:
  # Spring Boot 애플리케이션 (EC2 #1)
  - job_name: "spring-boot-app"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      # [서버 배포 시] 아래 변수를 실제 앱 서버 사설 IP로 변경해야 함
      - targets: ["${APP_SERVER_PRIVATE_IP}:8080"]
        labels:
          application: "festival-api"
          instance: "app-ec2"

  # Prometheus 자체 모니터링 (EC2 #2)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ✔ Node Exporter (EC2 #1)
  - job_name: "node-exporter-app"
    # [서버 배포 시] 아래 변수를 실제 앱 서버 사설 IP로 변경해야 함
    static_configs:
      - targets: ["${APP_SERVER_PRIVATE_IP}:9100"]
        labels:
          instance: "app-ec2"

  # Node Exporter (EC2 #2)
  - job_name: "node-exporter-observability"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          instance: "obs-ec2"
