name: Java CI with Gradle & Docker CD

on:
  push:
    branches: ["main", "dev"]
    paths:
     - 'src/**'
     - 'build.gradle'
     - 'settings.gradle'
     - 'Dockerfile'
     - '.github/workflows/**'

  pull_request:
    types: [opened, synchronize, closed]
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'Dockerfile'
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # 자바 17 설치 및 그레이들 캐싱
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # gradlew 실행 권한 주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 빌드 및 테스트 실행 (테스트 코드가 없어도 빌드는 수행함)
      # 'build' 명령어는 test를 포함하고 있어서, 나중에 테스트 코드 짜면 자동으로 같이 돕니다.
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Jar 파일 생성 (이미지 빌드용)
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 이미지 빌드 & 업로드
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dmsdnr0720/festival-api:latest

      # EC2 접속 & 실행 (여기서 EC2 내부의 .env를 읽음)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동
            cd /home/ubuntu/local-festival

            # 2. 최신 이미지 받기
            sudo docker pull dmsdnr0720/festival-api:latest

            # 3. 서비스 재실행
            sudo docker-compose -f docker-compose.prod.yml -f monitoring/docker-compose.promtail.yml down

            sudo docker-compose -f docker-compose.prod.yml -f monitoring/docker-compose.promtail.yml pull

            sudo docker-compose -f docker-compose.prod.yml -f monitoring/docker-compose.promtail.yml up -d

            # 4. 청소
            sudo docker image prune -f